// flow-typed signature: f45f4f87ff127a43545d31a47efff4dd
// flow-typed version: <<STUB>>/jsdom-no-contextify_v^3.1.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsdom-no-contextify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsdom-no-contextify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsdom-no-contextify/lib/jsdom' {
  declare module.exports: any;
}

declare module 'jsdom-no-contextify/lib/jsdom/browser/documentAdapter' {
  declare module.exports: any;
}

declare module 'jsdom-no-contextify/lib/jsdom/browser/documentfeatures' {
  declare module.exports: any;
}

declare module 'jsdom-no-contextify/lib/jsdom/browser/domtohtml' {
  declare module.exports: any;
}

declare module 'jsdom-no-contextify/lib/jsdom/browser/history' {
  declare module.exports: any;
}

declare module 'jsdom-no-contextify/lib/jsdom/browser/htmltodom' {
  declare module.exports: any;
}

declare module 'jsdom-no-contextify/lib/jsdom/browser/index' {
  declare module.exports: any;
}

declare module 'jsdom-no-contextify/lib/jsdom/browser/location' {
  declare module.exports: any;
}

declare module 'jsdom-no-contextify/lib/jsdom/browser/utils' {
  declare module.exports: any;
}

declare module 'jsdom-no-contextify/lib/jsdom/browser/Window' {
  declare module.exports: any;
}

declare module 'jsdom-no-contextify/lib/jsdom/contextify-shim' {
  declare module.exports: any;
}

declare module 'jsdom-no-contextify/lib/jsdom/level1/core' {
  declare module.exports: any;
}

declare module 'jsdom-no-contextify/lib/jsdom/level2/core' {
  declare module.exports: any;
}

declare module 'jsdom-no-contextify/lib/jsdom/level2/events' {
  declare module.exports: any;
}

declare module 'jsdom-no-contextify/lib/jsdom/level2/html' {
  declare module.exports: any;
}

declare module 'jsdom-no-contextify/lib/jsdom/level2/languages/javascript' {
  declare module.exports: any;
}

declare module 'jsdom-no-contextify/lib/jsdom/level2/style' {
  declare module.exports: any;
}

declare module 'jsdom-no-contextify/lib/jsdom/level3/core' {
  declare module.exports: any;
}

declare module 'jsdom-no-contextify/lib/jsdom/level3/ls' {
  declare module.exports: any;
}

declare module 'jsdom-no-contextify/lib/jsdom/level3/xpath' {
  declare module.exports: any;
}

declare module 'jsdom-no-contextify/lib/jsdom/living/character-data' {
  declare module.exports: any;
}

declare module 'jsdom-no-contextify/lib/jsdom/living/comment' {
  declare module.exports: any;
}

declare module 'jsdom-no-contextify/lib/jsdom/living/document-type' {
  declare module.exports: any;
}

declare module 'jsdom-no-contextify/lib/jsdom/living/document' {
  declare module.exports: any;
}

declare module 'jsdom-no-contextify/lib/jsdom/living/dom-implementation' {
  declare module.exports: any;
}

declare module 'jsdom-no-contextify/lib/jsdom/living/helpers/validate-names' {
  declare module.exports: any;
}

declare module 'jsdom-no-contextify/lib/jsdom/living/index' {
  declare module.exports: any;
}

declare module 'jsdom-no-contextify/lib/jsdom/living/node-filter' {
  declare module.exports: any;
}

declare module 'jsdom-no-contextify/lib/jsdom/living/node' {
  declare module.exports: any;
}

declare module 'jsdom-no-contextify/lib/jsdom/living/processing-instruction' {
  declare module.exports: any;
}

declare module 'jsdom-no-contextify/lib/jsdom/living/selectors' {
  declare module.exports: any;
}

declare module 'jsdom-no-contextify/lib/jsdom/living/text' {
  declare module.exports: any;
}

declare module 'jsdom-no-contextify/lib/jsdom/utils' {
  declare module.exports: any;
}

declare module 'jsdom-no-contextify/lib/jsdom/virtual-console' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsdom-no-contextify/lib/jsdom.js' {
  declare module.exports: $Exports<'jsdom-no-contextify/lib/jsdom'>;
}
declare module 'jsdom-no-contextify/lib/jsdom/browser/documentAdapter.js' {
  declare module.exports: $Exports<'jsdom-no-contextify/lib/jsdom/browser/documentAdapter'>;
}
declare module 'jsdom-no-contextify/lib/jsdom/browser/documentfeatures.js' {
  declare module.exports: $Exports<'jsdom-no-contextify/lib/jsdom/browser/documentfeatures'>;
}
declare module 'jsdom-no-contextify/lib/jsdom/browser/domtohtml.js' {
  declare module.exports: $Exports<'jsdom-no-contextify/lib/jsdom/browser/domtohtml'>;
}
declare module 'jsdom-no-contextify/lib/jsdom/browser/history.js' {
  declare module.exports: $Exports<'jsdom-no-contextify/lib/jsdom/browser/history'>;
}
declare module 'jsdom-no-contextify/lib/jsdom/browser/htmltodom.js' {
  declare module.exports: $Exports<'jsdom-no-contextify/lib/jsdom/browser/htmltodom'>;
}
declare module 'jsdom-no-contextify/lib/jsdom/browser/index.js' {
  declare module.exports: $Exports<'jsdom-no-contextify/lib/jsdom/browser/index'>;
}
declare module 'jsdom-no-contextify/lib/jsdom/browser/location.js' {
  declare module.exports: $Exports<'jsdom-no-contextify/lib/jsdom/browser/location'>;
}
declare module 'jsdom-no-contextify/lib/jsdom/browser/utils.js' {
  declare module.exports: $Exports<'jsdom-no-contextify/lib/jsdom/browser/utils'>;
}
declare module 'jsdom-no-contextify/lib/jsdom/browser/Window.js' {
  declare module.exports: $Exports<'jsdom-no-contextify/lib/jsdom/browser/Window'>;
}
declare module 'jsdom-no-contextify/lib/jsdom/contextify-shim.js' {
  declare module.exports: $Exports<'jsdom-no-contextify/lib/jsdom/contextify-shim'>;
}
declare module 'jsdom-no-contextify/lib/jsdom/level1/core.js' {
  declare module.exports: $Exports<'jsdom-no-contextify/lib/jsdom/level1/core'>;
}
declare module 'jsdom-no-contextify/lib/jsdom/level2/core.js' {
  declare module.exports: $Exports<'jsdom-no-contextify/lib/jsdom/level2/core'>;
}
declare module 'jsdom-no-contextify/lib/jsdom/level2/events.js' {
  declare module.exports: $Exports<'jsdom-no-contextify/lib/jsdom/level2/events'>;
}
declare module 'jsdom-no-contextify/lib/jsdom/level2/html.js' {
  declare module.exports: $Exports<'jsdom-no-contextify/lib/jsdom/level2/html'>;
}
declare module 'jsdom-no-contextify/lib/jsdom/level2/languages/javascript.js' {
  declare module.exports: $Exports<'jsdom-no-contextify/lib/jsdom/level2/languages/javascript'>;
}
declare module 'jsdom-no-contextify/lib/jsdom/level2/style.js' {
  declare module.exports: $Exports<'jsdom-no-contextify/lib/jsdom/level2/style'>;
}
declare module 'jsdom-no-contextify/lib/jsdom/level3/core.js' {
  declare module.exports: $Exports<'jsdom-no-contextify/lib/jsdom/level3/core'>;
}
declare module 'jsdom-no-contextify/lib/jsdom/level3/ls.js' {
  declare module.exports: $Exports<'jsdom-no-contextify/lib/jsdom/level3/ls'>;
}
declare module 'jsdom-no-contextify/lib/jsdom/level3/xpath.js' {
  declare module.exports: $Exports<'jsdom-no-contextify/lib/jsdom/level3/xpath'>;
}
declare module 'jsdom-no-contextify/lib/jsdom/living/character-data.js' {
  declare module.exports: $Exports<'jsdom-no-contextify/lib/jsdom/living/character-data'>;
}
declare module 'jsdom-no-contextify/lib/jsdom/living/comment.js' {
  declare module.exports: $Exports<'jsdom-no-contextify/lib/jsdom/living/comment'>;
}
declare module 'jsdom-no-contextify/lib/jsdom/living/document-type.js' {
  declare module.exports: $Exports<'jsdom-no-contextify/lib/jsdom/living/document-type'>;
}
declare module 'jsdom-no-contextify/lib/jsdom/living/document.js' {
  declare module.exports: $Exports<'jsdom-no-contextify/lib/jsdom/living/document'>;
}
declare module 'jsdom-no-contextify/lib/jsdom/living/dom-implementation.js' {
  declare module.exports: $Exports<'jsdom-no-contextify/lib/jsdom/living/dom-implementation'>;
}
declare module 'jsdom-no-contextify/lib/jsdom/living/helpers/validate-names.js' {
  declare module.exports: $Exports<'jsdom-no-contextify/lib/jsdom/living/helpers/validate-names'>;
}
declare module 'jsdom-no-contextify/lib/jsdom/living/index.js' {
  declare module.exports: $Exports<'jsdom-no-contextify/lib/jsdom/living/index'>;
}
declare module 'jsdom-no-contextify/lib/jsdom/living/node-filter.js' {
  declare module.exports: $Exports<'jsdom-no-contextify/lib/jsdom/living/node-filter'>;
}
declare module 'jsdom-no-contextify/lib/jsdom/living/node.js' {
  declare module.exports: $Exports<'jsdom-no-contextify/lib/jsdom/living/node'>;
}
declare module 'jsdom-no-contextify/lib/jsdom/living/processing-instruction.js' {
  declare module.exports: $Exports<'jsdom-no-contextify/lib/jsdom/living/processing-instruction'>;
}
declare module 'jsdom-no-contextify/lib/jsdom/living/selectors.js' {
  declare module.exports: $Exports<'jsdom-no-contextify/lib/jsdom/living/selectors'>;
}
declare module 'jsdom-no-contextify/lib/jsdom/living/text.js' {
  declare module.exports: $Exports<'jsdom-no-contextify/lib/jsdom/living/text'>;
}
declare module 'jsdom-no-contextify/lib/jsdom/utils.js' {
  declare module.exports: $Exports<'jsdom-no-contextify/lib/jsdom/utils'>;
}
declare module 'jsdom-no-contextify/lib/jsdom/virtual-console.js' {
  declare module.exports: $Exports<'jsdom-no-contextify/lib/jsdom/virtual-console'>;
}
