// flow-typed signature: a67dfa904594e4d778e65edc5f90158e
// flow-typed version: <<STUB>>/sanitize.css_v^4.1.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sanitize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'sanitize.css' {
  declare module.exports: any;
}
