// flow-typed signature: 2508d4d856ac9a8066a1242d0423241c
// flow-typed version: <<STUB>>/shed-css_v^1.0.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'shed-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'shed-css' {
  declare module.exports: any;
}
